// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdF8J13kL6VCp0vaeqmpOWPF_M-I7V39I',
    appId: '1:862797684853:web:117160b4624ae817d8583c',
    messagingSenderId: '862797684853',
    projectId: 'fashion-store-d716f',
    authDomain: 'fashion-store-d716f.firebaseapp.com',
    storageBucket: 'fashion-store-d716f.firebasestorage.app',
    measurementId: 'G-19Q5WC2E7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJaqR6gbBNQUj9JCUpJMBCq2iNZUhuh0g',
    appId: '1:862797684853:android:3ccfa3d53cc38b6bd8583c',
    messagingSenderId: '862797684853',
    projectId: 'fashion-store-d716f',
    storageBucket: 'fashion-store-d716f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTnW94tH6XGmJBINZDKSkF0-5NxYWfG_M',
    appId: '1:862797684853:ios:9dd802ac6decae80d8583c',
    messagingSenderId: '862797684853',
    projectId: 'fashion-store-d716f',
    storageBucket: 'fashion-store-d716f.firebasestorage.app',
    iosClientId: '862797684853-bgrhtedcvjvg5025n7fgc4huikkf9dts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTnW94tH6XGmJBINZDKSkF0-5NxYWfG_M',
    appId: '1:862797684853:ios:9dd802ac6decae80d8583c',
    messagingSenderId: '862797684853',
    projectId: 'fashion-store-d716f',
    storageBucket: 'fashion-store-d716f.firebasestorage.app',
    iosClientId: '862797684853-bgrhtedcvjvg5025n7fgc4huikkf9dts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdF8J13kL6VCp0vaeqmpOWPF_M-I7V39I',
    appId: '1:862797684853:web:ddfef4eaa3d53188d8583c',
    messagingSenderId: '862797684853',
    projectId: 'fashion-store-d716f',
    authDomain: 'fashion-store-d716f.firebaseapp.com',
    storageBucket: 'fashion-store-d716f.firebasestorage.app',
    measurementId: 'G-9JX5JND992',
  );
}
